import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/global/Header";
import { Footer } from "@/components/global/Footer";
import FlashMessage from "@/components/global/FlashMessage";
import { getFlashMessages } from "@/lib/flash";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const flashMessages = await getFlashMessages();
  
  return (
    <html lang="en">
      <body>
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased page`}>
          <Header />
          <FlashMessage initialMessages={flashMessages} />
          <div className="body" >
            {children}
          </div>
          <Footer />
          </div>
        </body>
    </html>
  );
}